### ISSUE TITLE
Update `requirements.txt`

### ISSUE THREAD

**Issue by Sayyad828** [ESBAAR-AI/Zalert_wits_producer#1]
- [x] add `sqlalchemy==2.0.19` to your requirements
- [x] add `psycopg2==2.9.7` to your requirements
- [x] specify the versions in `fastapi`, `uvicorn`, `pydantic`, `tqdm`.
- [x] Remove `datetime`, and `requests` as they are built-in packages in python already

**Comment by Nuran-A-Elsayed** [comment]
Updated!
